encoding: utf-8
baseurl: /
abouturl: pages/about.html
websitetilte: Life4Code
pygments: true

keywords: Java,Python,WEB开发,技术分享
description: life4code.com -- Life4Code分享技术文章和资源，专注Java和Python开发技术，专注于分布式，高性能开发和研究，Code改变生活，代码改变世界。

markdown:      maruku
markdown_ext:  markdown,mkd,mkdn,md




