encoding: utf-8
baseurl: /
abouturl: pages/about.html
websitetilte: Life4Code
pygments: true

keywords: Life4Code,WEB开发,Java,Python,技术分享
description: life4code.com -- Life4Code分享技术文章和资源，让Code改变生活，让代码改变世界，让互联网更加互联。Happy Coding，Happy Life!

markdown:      maruku
markdown_ext:  markdown,mkd,mkdn,md




